# Generated by Django 2.1.3 on 2018-12-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181214_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='channel_name',
            field=models.CharField(max_length=20),
        ),
    ]
